FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo
ENV HOME=/root
ENV XDG_RUNTIME_DIR=/tmp/runtime-root

# Make xdg runtime dir
RUN mkdir -p $XDG_RUNTIME_DIR && \
    chmod 700 $XDG_RUNTIME_DIR

# Install packages
RUN apt-get clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils \
    sudo \
    vim \
    nano \
    less \
    file \
    net-tools \
    iputils-ping \
    locales \
    git \
    wget \
    curl \
    build-essential

# Language preferences
RUN locale-gen en_US.UTF-8

# Add Ubuntu Universe repository and keys
RUN apt-get update && \
    apt-get install -y \
    software-properties-common
RUN add-apt-repository universe
RUN /bin/sh -c 'curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg'
RUN /bin/sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null'


# Install ROS packages
RUN apt-get update && \
    apt-get install -y \
    ros-humble-desktop \
    ros-dev-tools \
    ros-humble-rmw-cyclonedds-cpp 

# Install ros packages for RTL.
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-pip \
    python3-pytest \
    python3-pytest-cov \
    python3-rosdep \
    python3-setuptools \
    python3-vcstool \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN echo '\n\
source /opt/ros/humble/setup.bash\n\
' >> $HOME/.bashrc

WORKDIR $HOME
